#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

broadcastReplicas: 1
client:
  containerSecurityContext: {}
  extraEnv:
    OPAL_POLICY_STORE_URL: http://opa:8181
    # For postgres integration as datasource
    # OPAL_FETCH_PROVIDER_MODULES: opal_common.fetcher.providers,opal_fetcher_postgres.provider
  opaPort: 8181
  port: 7000
  replicas: 1
  securityContext: {}
  secrets:
    - opal-client-token-secret
image:
  client:
    registry: docker.io
    # Always use the standalone version
    # Use image quay.io/okdp/opal-client-standalone and tag 0.9.4-1.0-postgres for postgres integration as datasource
    repository: permitio/opal-client-standalone
    tag: 0.9.4
  pgsql:
    registry: docker.io
    repository: postgres
    tag: alpine
  server:
    registry: docker.io
    repository: permitio/opal-server
    tag: 0.9.4
openshift:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  enabled: false
  securityContext:
    fsGroup: 1010180000
    runAsGroup: 1010180000
    runAsUser: 1010180000
postgresql:
  containerSecurityContext: {}
  extraEnv: {}
  securityContext: {}
server:
  broadcastPgsql: true
  broadcastUri: null
  containerSecurityContext: {}
  dataConfigSources:
    config:
      entries: []
        # - url: "postgres://user:password@host:port/database"
        #   config:
        #     fetcher: "PostgresFetchProvider"
        #     query: "SELECT * from table_permissions;"
        #   topics:
        #     - "policy_data"
  secrets:
    - opal-ssh-secret
    - opal-master-token-secret
  # extraEnv:
    # OPAL_POLICY_REPO_WEBHOOK_SECRET: null
  policyRepoClonePath: null
  policyRepoMainBranch: master
  # If the policy repository is private set the ssh private key
  policyRepoSshKey:
  policyRepoUrl: https://github.com/OKDP/trino-opal-example-policy.git
  # Set to 0 if webhook is used
  pollingInterval: 30
  port: 7002
  replicas: 1
  securityContext: {}
  uvicornWorkers: 4
